name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        default: '1.0.0'

jobs:
  build-release:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.inputs.version }}
      OUTPUT_PATH: release
      ARTIFACT_NAME: release.tar.gz
    steps:
      - uses: actions/checkout@v3
      - name: package
        run: |
          mkdir -p ${{ env.OUTPUT_PATH }}
          cp README.md ${{ env.OUTPUT_PATH }}/README.md
          tar -zcvpf ${{ env.ARTIFACT_NAME }} ${{ env.OUTPUT_PATH }}
      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          name:  v${{ env.VERSION }}
          files: ${{ env.ARTIFACT_NAME }}
